name: Playwright Tests
on:
  push:
    branches: [main, master]
    paths:
      - "examples/sk/**"
      - "packages/surreal-better-auth/**"
  pull_request:
    branches: [main, master]
    paths:
      - "examples/sk/**"
      - "packages/surreal-better-auth/**"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      surrealdb:
        image: surrealdb/surrealdb:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          SURREAL_LOG: info
          SURREAL_USER: root
          SURREAL_PASS: root
        # Start SurrealDB with memory storage for testing
        cmd: start --log info --user root --pass root memory

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build adapter package
        run: bun run build
        working-directory: packages/surreal-better-auth

      - name: Install example dependencies
        run: bun install
        working-directory: examples/sk

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
        working-directory: examples/sk

      - name: Wait for SurrealDB to be ready
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:8000/health; do sleep 1; done'

      - name: Run Playwright tests
        run: bun run test:e2e
        working-directory: examples/sk
        env:
          CI: true
          SURREALDB_URL: http://localhost:8000
          SURREALDB_USER: root
          SURREALDB_PASS: root
          SURREALDB_NS: test
          SURREALDB_DB: test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: examples/sk/playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: examples/sk/test-results/
          retention-days: 30
