name: CI

on:
  push:
    branches: [ main, beta ]
  pull_request:
    branches: [ main, beta ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        runtime:
          - name: "Node.js 20"
            type: "node"
            version: "20"
          - name: "Node.js 22"
            type: "node"
            version: "22"
          - name: "Node.js 24"
            type: "node"
            version: "24"
          - name: "Bun latest"
            type: "bun"
            version: "latest"
            
    name: Test on ${{ matrix.runtime.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SurrealDB
        uses: surrealdb/setup-surreal@v2
        with:
          surrealdb_version: latest
          surrealdb_port: 8000
          surrealdb_username: root
          surrealdb_password: root
          surrealdb_log: info
          surrealdb_additional_args: --allow-all

      - name: Setup Node.js
        if: matrix.runtime.type == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.runtime.version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
      
      - name: Build package
        run: bun run build

      - name: Wait for SurrealDB
        run: |
          echo "Waiting for SurrealDB to become healthy..."
          until curl --fail http://localhost:8000/status; do
            echo "Waiting for SurrealDB..."
            sleep 1
          done
          echo "SurrealDB is up and running!"

      - name: Run adapter tests (Node.js)
        if: matrix.runtime.type == 'node'
        run: npm run test:adapter

      - name: Run adapter tests (Bun)
        if: matrix.runtime.type == 'bun'
        run: bun run test:adapter
        
      - name: Install example dependencies
        if: matrix.runtime.type == 'bun'
        working-directory: examples/sk
        run: bun install

      - name: Cache Playwright Browsers
        if: matrix.runtime.type == 'bun'
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        if: matrix.runtime.type == 'bun' && steps.cache-playwright.outputs.cache-hit != 'true'
        working-directory: examples/sk
        run: bunx playwright install --with-deps

      - name: Run integration tests
        if: matrix.runtime.type == 'bun'
        working-directory: examples/sk
        run: bunx playwright test
        env:
          CI: true
          SURREALDB_URL: http://localhost:8000
          SURREALDB_USER: root
          SURREALDB_PASS: root
          SURREALDB_NS: test
          SURREALDB_DB: example-sveltekit

      - name: Stop SurrealDB
        if: always()
        run: echo "Cleaning up... SurrealDB service will stop automatically."


  build:
    needs: test
    runs-on: ubuntu-latest
    name: Build and Upload Artifact

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: packages/surreal-better-auth/dist 
          retention-days: 7