name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - beta
      - main

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout code to get repository history and package.json
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: built-package
          run-id: ${{ github.event.workflow_run.id }}
          path: packages/surreal-better-auth/dist

      - name: Setup Bun for versioning scripts
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      # --- BETA ---
      - name: Get current version and increment beta
        if: github.event.workflow_run.head_branch == 'beta'
        id: version_beta
        run: |
          cd packages/surreal-better-auth
          CURRENT=$(node -p "require('./package.json').version")
          if [[ $CURRENT == *"-beta."* ]]; then
            NEW_VERSION=$(npm version prerelease --preid=beta --no-git-tag-version)
          else
            NEW_VERSION=$(npm version prerelease --preid=beta --no-git-tag-version)
          fi
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Publish beta to npm
        if: github.event.workflow_run.head_branch == 'beta'
        run: |
          cd packages/surreal-better-auth
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version bump and push (beta)
        if: github.event.workflow_run.head_branch == 'beta'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add packages/surreal-better-auth/package.json
          git commit -m "chore: bump version to ${{ steps.version_beta.outputs.version }} [skip ci]"
          git push

      - name: Create beta GitHub release
        if: github.event.workflow_run.head_branch == 'beta'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version_beta.outputs.version }}
          name: Beta Release ${{ steps.version_beta.outputs.version }}
          prerelease: true
          generate_release_notes: true

      # --- STABLE ---
      - name: Get version and make stable
        if: github.event.workflow_run.head_branch == 'main'
        id: version_stable
        run: |
          cd packages/surreal-better-auth
          CURRENT=$(node -p "require('./package.json').version")
          STABLE_VERSION=$(echo $CURRENT | sed 's/-beta\.[0-9]*//')
          npm version $STABLE_VERSION --no-git-tag-version
          echo "version=v$STABLE_VERSION" >> $GITHUB_OUTPUT
          echo "stable_version=$STABLE_VERSION" >> $GITHUB_OUTPUT

      - name: Publish stable to npm
        if: github.event.workflow_run.head_branch == 'main'
        run: |
          cd packages/surreal-better-auth
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit stable version, tag and push
        if: github.event.workflow_run.head_branch == 'main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add packages/surreal-better-auth/package.json
          git commit -m "chore: release stable version ${{ steps.version_stable.outputs.stable_version }} [skip ci]"
          git tag ${{ steps.version_stable.outputs.version }}
          git push
          git push --tags

      - name: Create stable GitHub release
        if: github.event.workflow_run.head_branch == 'main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version_stable.outputs.version }}
          name: Release ${{ steps.version_stable.outputs.stable_version }}
          generate_release_notes: true
