name: Sync README

on:
  push:
    branches: [main, beta]
    paths:
      - 'packages/surreal-better-auth/README.md'
  workflow_dispatch:

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync README
        run: |
          # Check if the placeholder exists in README.md
          if ! grep -q "<!-- include: packages/surreal-better-auth/README.md -->" README.md; then
            echo "Placeholder not found in README.md"
            exit 1
          fi
          
          # Replace the include placeholder with actual content
          if [ -f "packages/surreal-better-auth/README.md" ]; then
            # Create temp file with package content and fix image paths
            cp packages/surreal-better-auth/README.md /tmp/package-readme.md
            
            # Fix all relative paths starting with ./ to point to the correct location in monorepo
            sed -i 's|src="\./|src="./packages/surreal-better-auth/|g' /tmp/package-readme.md
            sed -i 's|srcset="\./|srcset="./packages/surreal-better-auth/|g' /tmp/package-readme.md
            sed -i 's|href="\./|href="./packages/surreal-better-auth/|g' /tmp/package-readme.md
            
            # Use sed to replace the include line with file content
            sed -i '/<!-- include: packages\/surreal-better-auth\/README\.md -->/r /tmp/package-readme.md' README.md
            sed -i '/<!-- include: packages\/surreal-better-auth\/README\.md -->/d' README.md
            
            echo "Successfully synced package README content"
          else
            echo "Package README.md not found"
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --quiet README.md; then
            echo "No changes to commit"
          else
            git add README.md
            git commit -m "docs: sync main README with package README [skip ci]"
            git push
          fi