name: Sync README

on:
  push:
    branches: [main, beta]
    paths:
      - 'packages/surreal-better-auth/README.md'
      - 'bottom.md'
  workflow_dispatch:

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync README
        run: |
          # Check if bottom.md template exists
          if [ ! -f "bottom.md" ]; then
            echo "Template file bottom.md not found"
            exit 1
          fi
          
          # Check if package README exists
          if [ ! -f "packages/surreal-better-auth/README.md" ]; then
            echo "Package README.md not found"
            exit 1
          fi
          
          # Create main README.md from bottom.md template
          echo "Creating main README.md from bottom.md template..."
          cp bottom.md README.md
          
          # Prepare package content with fixed image paths
          cp packages/surreal-better-auth/README.md /tmp/package-readme.md
          
          # Fix all relative paths starting with ./ to point to the correct location in monorepo
          sed -i 's|src="\./|src="./packages/surreal-better-auth/|g' /tmp/package-readme.md
          sed -i 's|srcset="\./|srcset="./packages/surreal-better-auth/|g' /tmp/package-readme.md
          sed -i 's|href="\./|href="./packages/surreal-better-auth/|g' /tmp/package-readme.md
          
          # Replace the include placeholder with actual content
          sed -i '/<!-- include: packages\/surreal-better-auth\/README\.md -->/r /tmp/package-readme.md' README.md
          sed -i '/<!-- include: packages\/surreal-better-auth\/README\.md -->/d' README.md
          
          echo "Successfully synced package README content"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --quiet README.md; then
            echo "No changes to commit"
          else
            git add README.md
            git commit -m "docs: sync main README with package README [skip ci]"
            git push
          fi